### ISSUE TITLE
Error in hexoskin upload

### ISSUE THREAD

**Issue by caraMsmith** [zross/sensorDataImport#54] opened 2017-08-28 15:40 UTC
I am getting the following error message when uploading a hexoskin file. I was able to upload 10 other ones today, but for some reason, this particular file won't open. Error message reads: "There is a problem with file BIKE2013_HXI10_S2-1_170727.zip. Error occurred in the processing step. No files uploaded successfully."

This file folder contains the same files as the other ones. Do you have any idea what could be the problem?  (Will email file)

**Comment by zross** [comment] 2017-08-28 16:55
Is it possible that that file is newer than the others. The error I see is:

>Decoder version [0, 6, 1]  too old. redownload decoder at: 'http://support.hexoskin.com/customer/portal/articles/1758581-how-do-i-convert-binary-data-downloaded-from-the-dashboard-'

Perhaps they changed the file type again or something and have a new decoder?

**Comment by caraMsmith** [comment] 2017-08-28 16:58
I don't think so because I downloaded files after that one that worked. Is is strange as to why this particular one isn't working

**Comment by zross** [comment] 2017-08-28 17:09
In my testing here (on a Mac) I think that is what the issue is. Even though the date at the link above is last year, when I downloaded and unzipped it looked like the program got updated just a few days ago. 

Perhaps the user for that file did something a little different and so the old decoder didn't work? I don't know. In any case, on my end I'm replacing the decoder. It's probably easiest if you do it manually on your end and then let me know if it fixed the issue:

1. Go to http://support.hexoskin.com/customer/portal/articles/1758581-how-do-i-convert-binary-data-downloaded-from-the-dashboard- download the Windows version
2. Replace the `exe` file at: sensorDataImport/inst/hexapps/windows (this is in your R packages directory)

**Comment by caraMsmith** [comment] 2017-08-28 17:23
I replaced the exe file, but am still getting that same error when uploading that file

**Comment by zross** [comment] 2017-08-28 17:32
I think it still might be that issue but the fact that it failed to finish processing previously might add an additional issue. When you run/upload a file can you look at the R console? I'd like to try and find the temp folder the app is writing to on your computer. If you can see the console see what it says under "Unzipped to folder ...." then delete anything in that temp folder and try running again.

Otherwise we might need to do a screen share.

**Comment by caraMsmith** [comment] 2017-08-28 17:53
I found the temp folder and deleted its contents, but still won't work. Are you free to share screens now via skype?

**Comment by zross** [comment] 2017-08-28 18:53
https://www.python.org/downloads/ if we need python

**Comment by caraMsmith** [comment] 2017-08-28 19:52
All 4 unzips had the 0.7.0 decoder

**Comment by zross** [comment] 2017-08-28 19:57
That makes more sense, but I'm confused about where the 0.5.3 came from now while we were on Skype.

**Comment by zross** [comment] 2017-08-29 17:58
I have a hack that probably works if you want to try it. Ultimately we might need to figure out why this file has a different decoder and whether we need to update. For now it looks like the old decoder can still do the processing if forced. So if I force a change of the decoder metadata the old decoder will do the processing. The code is:

```r
  info <- jsonlite::fromJSON(paste0(tmpdir, "/info.json")) 
  info$decoder_version <- "0.5.3"
  cat(jsonlite::toJSON(info, auto_unbox = TRUE), file = paste0(tmpdir, "/info.json"))
```

I can give you a gzip version of the package with this update if you want to finish up with the upload. Or, if you have time we can wait to hear what hexoskin people say.

**Comment by caraMsmith** [comment] 2017-08-29 18:12
Thanks Zev. We have some time so I'm going to wait to hear from hexoskin. Have a feeling they might be changing all the files to 0.7.0 and the one we had might have been a test file.

**Comment by zross** [comment] 2017-08-29 18:19
OK, we can wait, but a warning that I have some travel coming up so give me advance notice if you expect a crunch upload time.

**Comment by zross** [comment] 2017-09-13 13:27
I had a good conversation with Simon Dubeau, simon.dubeau@carretechnologies.com. He said it's an issue on his side related to Windows machines that he'll try to fix in a couple of days. He said it's perfectly valid at the moment to force the old decoder to process new files in the way that I have above (changing `info.json`) but, of course, if they learn about issues with some calculations in the future we'd want to use the new decoder.

So it's best to wait until he fixes the decoder, it did sound this would be fixed by Friday, Sept 15.

**Comment by zross** [comment] 2017-09-20 14:04
Simon says he fixed it, can you try updating the decoder and see if it works? http://support.hexoskin.com/customer/portal/articles/1758581-how-do-i-convert-binary-data-downloaded-from-the-dashboard-

**Comment by caraMsmith** [comment] 2017-09-20 19:06
It worked! Thank you!

**Comment by zross** [comment] 2017-09-20 19:09
Great, give it a day or two and then perhaps close this issue.

**Closed** 2017-09-27 19:17 UTC
